Repository openshift/cluster-operator, pull requests merged in 2018-07, with the labels that each got.

#277 Set openshift_node_config_name in userdata.
  contrib/examples/cluster-versions-template.yaml
  contrib/examples/clusterapi-template.yml
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
Labels: lgtm, size/S

#280 Use latest ansible 3.10 branch
  Makefile
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/XS

#282 Fix prefix for node config name in userdata
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
Labels: lgtm, size/S

#279 Skip cluster version template if clusterversion exists
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/S

#283 Use release-3.10 branch instead of master for cluster-operator-ansible build.
  build/cluster-operator-ansible/Dockerfile
Labels: lgtm, size/XS

#267 Refactor for cloud provider specific provider configs.
  contrib/cmd/aws-actuator-test/main.go
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
  contrib/examples/cluster-versions-template.yaml
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/image.go
  pkg/ansible/image_test.go
  pkg/ansible/jobgenerator.go
  pkg/ansible/jobgenerator_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/register.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/register.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.defaults.go
  pkg/apis/clusteroperator/validation/clusterdeployment.go
  pkg/apis/clusteroperator/validation/clusterdeployment_test.go
  pkg/apis/clusteroperator/validation/clusterversion.go
  pkg/apis/clusteroperator/validation/clusterversion_test.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/awselb/aws_elb_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterinstall/controller.go
  pkg/controller/combinedcluster.go
  pkg/controller/components/components_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/controller/deployclusterapi/deployclusterapi_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/infra/infra_controller_test.go
  pkg/controller/master/master_controller.go
  pkg/controller/nodeconfig/nodeconfig_controller.go
  pkg/controller/nodeconfig/nodeconfig_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/clusterversion/storage_test.go
  test/integration/controller_test.go
  test/integration/jobutils.go
  test/integration/waitutils.go
Labels: lgtm, size/XXL

#285 Stop bypassing cluster deployments in integration tests.
  test/integration/controller_test.go
Labels: lgtm, size/L

#286 Increase retries on checking if cluster versions should be created.
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/XS

#289 Skip remote machineset cleanup when sync never happend
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/M

#290 Fix check for clusterversion existence
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/XS

#291 Drop deprecated new cluster API path, only build images if we're pushing.
  contrib/ansible/create-cluster-playbook.yml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/examples/clusterapi-template.yml
Labels: lgtm, size/L

#292 Hookup pod and service network CIDRs in the API.
  contrib/examples/cluster-deployment-template.yaml
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/defaults.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/validation/clusterdeployment.go
  pkg/apis/clusteroperator/validation/clusterdeployment_test.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/controller/controller_utils.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/clusterdeployment/storage_test.go
Labels: lgtm, size/L

#293 Utility to wait for existence and ready status of an API service
  Makefile
  contrib/ansible/deploy-devel-playbook.yml
  contrib/cmd/wait-for-apiservice/waitforservice.go
Labels: lgtm, size/L

#296 Fix cluster deployment template subnets
  contrib/examples/cluster-deployment-template.yaml
Labels: lgtm, size/XS

#298 Remove ClusterID field from MachineSetSpec
  contrib/cmd/aws-actuator-test/main.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/clusterapi/aws/utils.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/awselb/aws_elb_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/M

#300 Use aws-machine-controller binary on target cluster
  Makefile
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/.gitignore
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
Labels: lgtm, size/M

#299 Create per-cluster iam roles for master and node instances.
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/infrastructure.yml
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/uninstall_iam.yml
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/uninstall_infrastructure.yml
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/M

#302 Mount aws-machine-controller binary only in development case
  Makefile
  build/cluster-operator-ansible/playbooks/cluster-api-prep/.gitignore
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-common.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-development.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-production.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/machine-controller-template-dev.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/machine-controller-template.yaml
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/L

#301 Change CD.Spec.ClusterID to CD.Spec.ClusterName
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/validation/clusterdeployment.go
  pkg/apis/clusteroperator/validation/clusterdeployment_test.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/controller/awselb/aws_elb_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/clusterdeployment/storage_test.go
  pkg/registry/clusteroperator/clusterdeployment/strategy.go
  test/integration/controller_test.go
Labels: lgtm, size/L

#303 Remove unused label consts.
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
Labels: lgtm, size/M

#304 Add public ssh key to cluster create
  contrib/ansible/create-cluster-playbook.yml
  contrib/examples/cluster-deployment-template.yaml
  pkg/ansible/generate.go
  pkg/ansible/jobgenerator.go
Labels: lgtm, size/M

#305 Honor VPC name and Subnet in AWS hardware spec
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/roles/openshift_aws/tasks/security_group.yml
  pkg/ansible/generate.go
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/M

#295 Hook up SDN plugin name.
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/defaults.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/validation/clusterdeployment.go
  pkg/apis/clusteroperator/validation/clusterdeployment_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/clusterdeployment/storage_test.go
Labels: lgtm, size/M

#308 stop including ansible vars with '-e'
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/run
  contrib/fake-openshift-ansible/fake-openshift-ansible
  pkg/ansible/generate.go
  pkg/ansible/jobgenerator.go
Labels: lgtm, size/XL

#307 Consolidate separate utilities under single command
  Makefile
  README.md
  build/playbook-mock/Dockerfile
  contrib/ansible/deploy-devel-playbook.yml
  contrib/cmd/cluster-api-export/export.go
  contrib/cmd/coutil/main.go
  contrib/examples/deploy-playbook-mock.yaml
  contrib/pkg/actuator/actuatortest.go
  contrib/pkg/apiservice/waitforservice.go
  contrib/pkg/cluster/waitforcluster.go
  contrib/pkg/jenkins/main.go
  contrib/pkg/jenkins/util/dockerinfo.go
  contrib/pkg/jenkins/util/download.go
  contrib/pkg/jenkins/util/extractlogs.go
  contrib/pkg/playbookmock/cmd.go
  contrib/pkg/playbookmock/server.go
Labels: lgtm, size/XXL

#306 Avoid cloud ssh public key name collision
  cmd/cluster-operator-apiserver/app/testing/server_test.go
  contrib/ansible/create-cluster-playbook.yml
  contrib/examples/cluster-deployment-template.yaml
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/registry/clusteroperator/clusterdeployment/storage_test.go
  pkg/registry/clusteroperator/clusterdeployment/strategy.go
  pkg/registry/clusteroperator/clusterdeployment/strategy_test.go
Labels: lgtm, size/L
