Repository openshift/cluster-operator, pull requests merged in 2018-06, with the labels that each got.

#241 ClusterDeployment controller
  cmd/cluster-operator-apiserver/app/testing/server_test.go
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  contrib/examples/cluster-deployment-template.yaml
  contrib/examples/clusterapi-template.yml
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/validation/clusterdeployment.go
  pkg/apis/clusteroperator/validation/clusterdeployment_test.go
  pkg/apis/componentconfig/types.go
  pkg/clusterapi/aws/actuator.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/combinedcluster.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/controller/infra/infra_controller_test.go
  pkg/registry/clusteroperator/clusterdeployment/storage_test.go
Labels: lgtm, size/XXL

#248 Temporarily allow infra deprovision without deleting remote machinesets.
  pkg/controller/infra/infra_controller.go
Labels: lgtm, size/XS

#247 Add controller to add masters to internal/external ELB.
  Makefile
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/apis/componentconfig/types.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/utils.go
  pkg/clusterapi/aws/utils_test.go
  pkg/controller/awselb/aws_elb_controller.go
  test/integration/controller_test.go
Labels: lgtm, size/XL

#250 Fix update of machineset replicas on clusterdeployment sync
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/L

#249 Create a fake cluster operator environment by default
  Makefile
  README.md
  build/fake-machine-controller/Dockerfile
  cmd/fake-machine-controller/machine-controller.go
  contrib/ansible/create-cluster-playbook.yml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/ansible/deploy-playbook.yml
  contrib/examples/cluster-api-controllers-template.yaml
  contrib/examples/cluster-versions-template.yaml
  pkg/clusterapi/fake/actuator.go
Labels: lgtm, size/L

#252 Fix delete machine bug.
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/utils.go
Labels: lgtm, size/XS

#254 Include "undo" in the name of undo jobs
  pkg/controller/jobcontrol.go
  pkg/controller/jobcontrol_test.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/mockjobcontrol_generated_test.go
Labels: lgtm, size/L

#253 Fix master machine security groups and add AWS actuator create tests.
  build/generate-mocks.sh
  contrib/cmd/aws-actuator-test/main.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/clusterapi/aws/client.go
  pkg/clusterapi/aws/client_generated_test.go
  pkg/clusterapi/aws/utils.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/controller_utils.go
Labels: lgtm, size/XXL

#255 Use clusterID instead of name for identifying the cluster in the cloud.
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/validation/clusterdeployment.go
  pkg/apis/clusteroperator/validation/clusterdeployment_test.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/clusterapi/aws/utils.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/clusterdeployment/storage_test.go
  pkg/registry/clusteroperator/clusterdeployment/strategy.go
  test/integration/controller_test.go
Labels: lgtm, size/L

#256 Add UpdateMachine tests for AWS actuator.
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
Labels: lgtm, size/L

#246 machine set / cluster syncing controller
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/apis/componentconfig/types.go
  pkg/controller/controller_utils.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: lgtm, size/XXL

#258 AWS actuator: use correct IAM role
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/S

#259 Add unit tests for AWS actuator delete.
  pkg/clusterapi/aws/actuator_test.go
Labels: lgtm, size/M

#260 Remove AWS credentials before syncing cluster/machinesets
  pkg/controller/controller_utils.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: lgtm, size/S

#262 Create master and node iam roles within the infrastructure playbook.
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/infrastructure.yml
  pkg/ansible/generate.go
Labels: lgtm, size/M

#263 Change cluster name from clusterDeployment.Name to clusterDeployment.Spec.ClusterID
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: lgtm, size/S

#264 Fix the OpenShift Ansible link.
  README.md
Labels: lgtm, size/XS

#265 Move iam variables to infrastructure playbook.
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/infrastructure.yml
  pkg/ansible/generate.go
Labels: lgtm, size/S

#266 Update README.md to include more setup information
  README.md
Labels: lgtm, size/S

#261 Only attempt to re-add masters to ELBs after period of time.
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/clusterapi/aws/client.go
  pkg/clusterapi/aws/mock/client_generated.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/awselb/aws_elb_controller_test.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
Labels: lgtm, size/XL

#269 Skip role creation on infra
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/infrastructure.yml
Labels: lgtm, size/M

#270 Remove --incluster from cluster-api-controller-manager command.
  contrib/examples/cluster-api-controllers-template.yaml
Labels: lgtm, size/XS

#271 Update wait-for-cluster-ready command
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
Labels: lgtm, size/M

#272 Change node instances to 'terminate' by default.
  .gitignore
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
Labels: lgtm, size/M

#273 Leverage shorter ELB suffixes in Openshift Ansible
  pkg/ansible/generate_test.go
  pkg/controller/controller_utils.go
Labels: lgtm, size/S

#274 Fix aws-actuator-test
  contrib/cmd/aws-actuator-test/main.go
Labels: lgtm, size/XS

#275 Wait for cluster to be created when waiting for it to be ready
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
Labels: lgtm, size/S

#276 Detect and terminate stopped nodes
  .gitignore
  contrib/cmd/aws-actuator-test/main.go
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/clusterapi/aws/utils.go
Labels: lgtm, size/L

#278 Introduce separate flag to build images on deployment
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/XS

#281 handle running controller-manager in debug session
  cmd/cluster-operator/controller-manager.go
  cmd/cluster-operator/main.go
Labels: lgtm, size/S
