Repository openshift/cluster-operator, pull requests merged in 2018-04, with the labels that each got.

#126 cluster-api installer
  Makefile
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/cluster-api-prep/deploy-cluster-api.yaml
  build/cluster-operator-ansible/cluster-api-prep/files/cluster-api-template.yaml
Labels: lgtm, size/L

#130 use DeploymentType from ClusterVersion
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
Labels: lgtm, size/L

#133 Fix ansible image due to ansible v2.5 changes
  build/cluster-operator-ansible/Dockerfile
Labels: lgtm, size/S

#134 Ignore customized local cluster yaml
  .gitignore
Labels: lgtm, size/XS

#135 Collapse vars used to set instance type and asg size
  pkg/ansible/generate.go
Labels: lgtm, size/M

#131 Add a controller to periodically deploy the kube cluster API controllers.
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/controller/deployclusterapi/deployclusterapi_controller.go
  pkg/controller/jobcontrol_test.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/XL

#138 idempotentize cluster-api-template
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
Labels: lgtm, size/S

#137 AWS machine controller for cluster API
  Makefile
  cmd/aws-machine-controller/machine-controller.go
  contrib/cmd/aws-actuator-test/main.go
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/XL

#141 Add a tagSpecification for the instance volume.
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/XS

#142 Machine controller deployment
  Makefile
  build/aws-machine-controller/Dockerfile
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
Labels: lgtm, size/L

#143 Export cluster API resources
  contrib/cmd/cluster-api-export/export.go
Labels: lgtm, size/L

#146 Enable auto approval of node CSRs
  pkg/ansible/generate.go
Labels: lgtm, size/XS

#145 Fix AWS actuator, double-encoding of bootstrap kubeconfig
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/M

#144 Secret creation serviceaccount
  contrib/examples/deploy.yaml
  pkg/ansible/jobgenerator.go
  pkg/controller/master/master_controller.go
Labels: lgtm, size/L

#148 README updates related to our custom Ansible image.
  README.md
  contrib/examples/cluster.yaml
Labels: lgtm, size/M

#151 Bump test cluster instance type to t2.xlarge.
  contrib/examples/cluster.yaml
Labels: lgtm, size/XS

#149 Generate certs if secrets do not exist.
  contrib/ansible/deploy-devel.yaml
  contrib/examples/deploy.yaml
Labels: lgtm, size/L

#154 Extract AWS creds secret from template.
  contrib/ansible/deploy-devel.yaml
  contrib/examples/deploy.yaml
  pkg/ansible/jobgenerator.go
Labels: lgtm, size/M

#156 Allow specifying a cluster name
  contrib/examples/create-cluster.sh
Labels: lgtm, size/XS

#153 Add a PersistentVolumeClaim for our apiserver etcd instance.
  contrib/examples/deploy.yaml
Labels: lgtm, size/S

#155 Fix fake-ansible image missing our playbooks.
  Makefile
  build/fake-openshift-ansible/Dockerfile
Labels: lgtm, size/XS

#158 Create etcd pvc in cluster operator namespace
  contrib/examples/deploy.yaml
Labels: lgtm, size/XS

#157 Override openshift_hosted_router_edits to enable ROUTER_USE_PROXY_PROTOCOL.
  pkg/ansible/generate.go
Labels: lgtm, size/S

#162 Add a command to wait for cluster installed status
  Makefile
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
Labels: lgtm, size/L

#160 More changes to support deployment to CI cluster
  README.md
  contrib/ansible/deploy-playbook.yaml
  contrib/examples/cluster-operator-roles-template.yaml
  contrib/examples/cluster-operator-template.yaml
  contrib/examples/create-cluster.sh
Labels: lgtm, size/L

#161 Update cluster running status when provisioning has completed
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/controller/machineset/machineset_controller.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
Labels: lgtm, size/L

#163 Set the current context of the cluster kubeconfig to the external one
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/install_masters.yml
Labels: lgtm, size/XS

#159 building various cluster-operator-ansible images
  Makefile
  contrib/examples/cluster.yaml
  contrib/examples/create-cluster.sh
Labels: lgtm, size/M

#164 Make the infra selector match node labels
  pkg/ansible/generate.go
Labels: lgtm, size/XS

#165 Set number of docker registry replicas
  pkg/ansible/generate.go
Labels: lgtm, size/XS

#167 Override openshift_master_cluster_public_hostname as the external ELB hostname.
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/roles/openshift_aws/tasks/master_facts.yml
Labels: lgtm, size/M

#166 Create cluster refactor
  README.md
  contrib/ansible/create-cluster-playbook.yaml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/ansible/deploy-playbook.yaml
  contrib/examples/cluster-template.yaml
  contrib/examples/cluster-versions-template.yaml
  contrib/examples/cluster.yaml
  contrib/examples/create-cluster.sh
  pkg/ansible/generate.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/XL

#171 Replace use of openssl_certificate with a custom certgen Ansible role.
  .gitignore
  contrib/ansible/create-cluster-playbook.yaml
  contrib/ansible/deploy-playbook.yaml
  contrib/ansible/roles/cluster_operator_certgen/files/ca-config.json
  contrib/ansible/roles/cluster_operator_certgen/tasks/main.yml
  contrib/ansible/roles/cluster_operator_certgen/templates/ca-setup.json.j2
  contrib/ansible/roles/cluster_operator_certgen/templates/cert-config.json.j2
  contrib/ansible/roles/cluster_operator_certgen/vars/main.yml
  contrib/apiserver-aggregation-tls-setup.sh
Labels: lgtm, size/L

#173 Ensure certs dir exists when deploying cluster-operator
  contrib/ansible/deploy-playbook.yaml
Labels: lgtm, size/XS

#175 README updates for Mac
  README.md
Labels: lgtm, size/S

#168 Kubectl apply module
  README.md
  contrib/ansible/create-cluster-playbook.yaml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/ansible/deploy-playbook.yaml
Labels: lgtm, size/L

#172 set registry count to the number of infra nodes (max 2)
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/controller/components/components_controller.go
Labels: lgtm, size/M

#177 Convert to builds, image streams and deployment configs.
  Dockerfile
  Makefile
  README.md
  contrib/ansible/create-cluster-playbook.yaml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/ansible/deploy-playbook.yaml
  contrib/examples/cluster-operator-roles-template.yaml
  contrib/examples/cluster-operator-template.yaml
Labels: lgtm, size/L

#178 Revert "Override openshift_master_cluster_public_hostname as the external ELB hostname."
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/roles/openshift_aws/tasks/master_facts.yml
Labels: lgtm, size/M

#170 Wait for deployments to complete before installing cluster versions
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/XS

#180 Update make build target for kubernetes-cluster-api image
  Makefile
Labels: lgtm, size/XS
