Repository openshift/cluster-operator, pull requests merged in 2018-05, with the labels that each got.

#182 Standardize on .yml for ansible playbooks and update README to match.
  README.md
  contrib/ansible/create-cluster-playbook.yml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/ansible/deploy-playbook.yml
Labels: lgtm, size/XS

#184 Fixes to cluster-api deployment and export
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
  contrib/cmd/cluster-api-export/export.go
Labels: lgtm, size/XS

#186 AWS actuator: remove finalizer on successful delete
  contrib/cmd/aws-actuator-test/main.go
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/M

#187 Parameterize AWS SSH keypair name
  contrib/ansible/create-cluster-playbook.yml
  contrib/examples/cluster-template.yaml
Labels: lgtm, size/S

#193 Start a cluster-api informer in controller manager
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  pkg/controller/client_builder.go
Labels: lgtm, size/M

#194 Add check that controller-manager can use to verify that cluster-api resources are available
  cmd/cluster-operator-controller-manager/app/controllermanager.go
Labels: lgtm, size/M

#200 Start cluster-api informers in controller-manager
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  contrib/examples/cluster-operator-roles-template.yaml
Labels: lgtm, size/XS

#199 Add utility to extract e2e test container logs
  contrib/cmd/extract-co-jenkins-logs/main.go
  contrib/cmd/extract-co-jenkins-logs/util/dockerinfo.go
  contrib/cmd/extract-co-jenkins-logs/util/download.go
  contrib/cmd/extract-co-jenkins-logs/util/extractlogs.go
Labels: lgtm, size/L

#202 Stop wrapping RESTOptions for cluster-api unneccessarily
  pkg/apiserver/etcd_config.go
Labels: lgtm, size/S

#195 Fix infinitely stalled devel deployment.
  contrib/ansible/create-cluster-playbook.yml
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/M

#203 Deploy AWS actuator from source in root CO cluster.
  Makefile
  build/cluster-operator/Dockerfile
  contrib/examples/cluster-api-controllers-template.yaml
Labels: lgtm, size/M

#204 Provide a means for adding custom validation
  pkg/apis/clusterapi/validation/machine.go
  pkg/apis/clusterapi/validation/validation.go
  pkg/apiserver/etcd_config.go
Labels: lgtm, size/L

#190 Small roles template cleanup and maintenance note.
  README.md
  contrib/examples/cluster-operator-roles-template.yaml
Labels: lgtm, size/XS

#208 Provide function for patch cluster-api Cluster status
  pkg/controller/client_utils.go
Labels: lgtm, size/M

#207 Regenerate the generated mock files
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
Labels: lgtm, size/L

#206 Remove unneeded auto-generated client files
  pkg/client/informers_generated/internalversion/v1alpha1/interface.go
  pkg/client/informers_generated/internalversion/v1alpha1/internalversion/cluster.go
  pkg/client/informers_generated/internalversion/v1alpha1/internalversion/clusterversion.go
  pkg/client/informers_generated/internalversion/v1alpha1/internalversion/interface.go
  pkg/client/informers_generated/internalversion/v1alpha1/internalversion/machine.go
  pkg/client/informers_generated/internalversion/v1alpha1/internalversion/machineset.go
  pkg/client/listers_generated/v1alpha1/internalversion/cluster.go
  pkg/client/listers_generated/v1alpha1/internalversion/clusterversion.go
  pkg/client/listers_generated/v1alpha1/internalversion/expansion_generated.go
  pkg/client/listers_generated/v1alpha1/internalversion/machine.go
  pkg/client/listers_generated/v1alpha1/internalversion/machineset.go
Labels: lgtm, size/XL

#209 Document how to run controllers locally for development productivity.
  README.md
Labels: lgtm, size/S

#212 Check availability of cluster API resources
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  pkg/controller/client_builder.go
Labels: lgtm, size/L

#213 infra controller for cluster-api
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.defaults.go
  pkg/controller/client_utils.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_controller_test.go
  pkg/controller/combinedcluster.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/infra/infra_controller_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
  test/integration/waitutils.go
Labels: lgtm, size/XL

#211 Small changes working towards AWS actuator working on master.
  Makefile
  contrib/examples/clusterapi-template.yml
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/M

#220 use 'shell' so we can inherit GOPATH (if set)
  contrib/ansible/deploy-devel-playbook.yml
Labels: lgtm, size/XS

#221 document need for python2-libselinux
  README.md
Labels: lgtm, size/XS

#214 Delete target machinesets
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/jobsync.go
  pkg/controller/jobsyncstrategy.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/L

#222 Wait for remote api deployment to have ready replicas.
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
Labels: lgtm, size/S

#223 Use global IAM role names
  pkg/ansible/generate.go
Labels: lgtm, size/S

#183 Sync machine sets
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/apis/componentconfig/types.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
  pkg/controller/syncmachineset/syncmachineset_controller.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
Labels: lgtm, size/XL

#228 Add cluster API and machine controller image refs to ClusterVersion
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/L

#224 cluster-api for all master-installing controllers
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/clusterinstall/controller.go
  pkg/controller/clusterinstall/installstrategy.go
  pkg/controller/combinedcluster.go
  pkg/controller/components/components_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/deployclusterapi/deployclusterapi_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/jobsyncstrategy.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
  pkg/controller/nodeconfig/nodeconfig_controller.go
  pkg/controller/nodeconfig/nodeconfig_controller_test.go
  pkg/controller/syncmachineset/syncmachineset_controller.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
  pkg/logging/logging.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
  test/integration/jobutils.go
  test/integration/waitutils.go
Labels: lgtm, size/XXL

#229 Ensure cluster API binaries are executable in image
  build/clusterapi-image/Dockerfile
Labels: lgtm, size/XS

#232 Check for cluster readiness in cluster controller
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
Labels: lgtm, size/L

#225 Use AWS credentials for actuator EC2 client when defined.
  pkg/clusterapi/aws/actuator.go
  pkg/controller/clusterapimachine/machine_controller.go
  pkg/controller/controller_utils.go
Labels: lgtm, size/L

#230 Parameterize images to deploy on target cluster
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
  contrib/ansible/deploy-devel-playbook.yml
  contrib/examples/cluster-versions-template.yaml
  pkg/ansible/generate.go
Labels: lgtm, size/L

#231 Integration tests using CAPI
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/controller/client_utils.go
  pkg/controller/clusterapimachine/machine_controller.go
  pkg/controller/clusterinstall/controller.go
  pkg/controller/components/components_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/infra/infra_controller_test.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/syncmachineset/syncmachineset_controller.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
  test/integration/controller_test.go
  test/integration/jobutils.go
  test/integration/waitutils.go
Labels: lgtm, size/XXL

#235 Fix compile error from merge
  pkg/ansible/generate.go
Labels: size/S

#233 Verify that generated mocks are up-to-date
  Makefile
  build/generate-mocks.sh
Labels: lgtm, size/M

#236 Fix infra controller lookup of infra machineset size.
  pkg/controller/components/components_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/infra/infra_controller_test.go
  test/integration/controller_test.go
Labels: lgtm, size/L

#234 Additional fixes for prod like deployments.
  contrib/ansible/deploy-playbook.yml
  contrib/examples/cluster-api-controllers-template.yaml
  contrib/examples/cluster-operator-roles-template.yaml
  contrib/examples/cluster-operator-template.yaml
Labels: lgtm, size/S

#238 Fix AWS actuator to tag instances as required.
  pkg/clusterapi/aws/actuator.go
Labels: lgtm, size/M

#239 Fix clusterapi template master role and provider config.
  contrib/examples/clusterapi-template.yml
Labels: lgtm, size/S

#240 Update image for cluster API controllers in root cluster.
  contrib/ansible/deploy-playbook.yml
  contrib/examples/cluster-api-controllers-template.yaml
Labels: lgtm, size/XS

#243 Fix verify-mocks refusing to run due to untracked files.
  Makefile
Labels: lgtm, size/XS

#242 Update machine status and allow for master deletion in root cluster.
  contrib/examples/cluster-api-controllers-template.yaml
  pkg/apis/clusteroperator/register.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/register.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/clusterapi/aws/actuator.go
  pkg/controller/controller_utils.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/XL
