Repository openshift/cluster-operator, pull requests merged in 2018-02, with the labels that each got.

#86 Convert region AMIs to a list.
  contrib/examples/cluster.yaml
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/validation/clusterversion.go
  pkg/apis/clusteroperator/validation/clusterversion_test.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/controller/cluster/cluster_controller_test.go
  pkg/controller/infra/infra_controller.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/clusterversion/storage_test.go
  test/integration/controller_test.go
Labels: lgtm, size/L

#85 Allow machineset scaling
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_controller_test.go
Labels: lgtm, size/L

#90 Generate unit test mocks as part of make test-unit
  Makefile
  build/build-image/Dockerfile
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
Labels: lgtm, size/L

#87 Run all playbook jobs in parallel
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
Labels: lgtm, size/L

#91 Add SSHUser to cluster hardware info.
  contrib/examples/cluster.yaml
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/defaults.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/M

#92 Verify generated files as part of make verify
  Makefile
  build/update-apiserver-gen.sh
Labels: lgtm, size/L

#95 Add cloudprovider configuration which references AWS credentials via job environment.
  pkg/ansible/generate.go
Labels: lgtm, size/XS

#93 Add controller to install components on master
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/ansible/generate.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/controller/components/components_controller.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/XL

#88 Deprovision clusters and machine sets
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/components/components_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/jobcontrol.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/jobsyncstrategy.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
  test/integration/controller_test.go
  test/integration/jobutils.go
  test/integration/waitutils.go
Labels: lgtm, size/XXL

#97 Circumvent long delays in job completion after pod success
  pkg/ansible/jobgenerator.go
  pkg/controller/jobcontrol.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
Labels: lgtm, size/L

#100 allow providing custom ssh key and custom cluster definition
  contrib/ansible/deploy-devel.yaml
  contrib/examples/create-cluster.sh
Labels: lgtm, size/S

#101 add default vpc settings
  pkg/ansible/generate.go
Labels: lgtm, size/M

#103 use new infra uninstaller
  pkg/controller/infra/infra_controller.go
Labels: lgtm, size/XS

#102 Restart jobs when they fail
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/components/components_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/jobcontrol.go
  pkg/controller/jobcontrol_test.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/jobsyncstrategy.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
  pkg/openapi/openapi_generated.go
  test/integration/jobutils.go
  test/integration/waitutils.go
Labels: lgtm, size/XL

#105 Hookup deprovisioning playbook
  contrib/examples/cluster.yaml
  pkg/controller/machineset/machineset_controller.go
Labels: lgtm, size/S

#107 Fix data race in integration test
  test/integration/controller_test.go
Labels: lgtm, size/XS

#108 Delete machinesets in cluster controller
  pkg/controller/cluster/cluster_controller.go
Labels: lgtm, size/S

#110 trying to use a password-protected ssh key isn't supported
  contrib/ansible/deploy-devel.yaml
Labels: lgtm, size/S
