Repository openshift/cluster-operator, pull requests merged in 2018-09, with the labels that each got.

#337 Add coutil verify-import subcommand.
  build/verify-imports/import-rules.yaml
  contrib/cmd/coutil/main.go
  contrib/pkg/verification/imports.go
Labels: lgtm, size/L

#338 Add coutil verify-import to make verify.
  Makefile
Labels: lgtm, size/XS

#339 label-based uninstaller
  contrib/cmd/coutil/main.go
  contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
Labels: lgtm, size/XXL
