Repository openshift/cluster-operator, pull requests merged in 2018-03, with the labels that each got.

#111 Fix deploy when libra.pem not pass protected.
  contrib/ansible/deploy-devel.yaml
Labels: lgtm, size/XS

#96 Complete functional cluster version installs.
  contrib/examples/cluster.yaml
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/validation/clusterversion.go
  pkg/apis/clusteroperator/validation/clusterversion_test.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_controller_test.go
  pkg/controller/components/components_controller.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
Labels: lgtm, size/XL

#114 #98. Restart job pods on failure
  pkg/ansible/jobgenerator.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/components/components_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/jobcontrol.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/jobsyncstrategy.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/controller/mockjobsyncstrategy_generated_test.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/L

#116 Run each components playbook in parallel in a separate container
  pkg/ansible/jobgenerator.go
  pkg/ansible/jobgenerator_test.go
  pkg/controller/components/components_controller.go
Labels: do-not-merge/blocked-paths, lgtm, size/L

#117 Use an openshift-ansible image appropriate for a ClusterVersion
  README.md
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  contrib/ansible/deploy-devel.yaml
  contrib/examples/cluster.yaml
  contrib/examples/create-cluster.sh
  contrib/examples/deploy.yaml
  pkg/ansible/image.go
  pkg/ansible/image_test.go
  pkg/ansible/jobgenerator.go
  pkg/ansible/jobgenerator_test.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/validation/clusterversion.go
  pkg/apis/clusteroperator/validation/clusterversion_test.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/components/components_controller.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/infra/infra_controller_test.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/controller/mockjobcontrol_generated_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
Labels: lgtm, size/XL

#118 Use openshift-cluster-operator as the namespace
  README.md
  cmd/cluster-operator-apiserver/app/testing/server_test.go
  contrib/ansible/deploy-devel.yaml
  contrib/apiserver-aggregation-tls-setup.sh
  contrib/examples/cluster.yaml
  contrib/examples/create-cluster.sh
  contrib/examples/deploy.yaml
  contrib/examples/get-playbook-mock-runs.sh
  contrib/fake-openshift-ansible/fake-openshift-ansible
  pkg/apis/clusteroperator/validation/cluster_test.go
  pkg/apis/clusteroperator/validation/machineset_test.go
  pkg/registry/clusteroperator/cluster/storage_test.go
Labels: lgtm, size/M

#119 Fix checked-in conflict in ansible deploy playbook.
  contrib/ansible/deploy-devel.yaml
Labels: lgtm, size/XS

#121 Switch to t2.medium for test cluster.
  contrib/examples/cluster.yaml
Labels: lgtm, size/XS

#123 Add target for upstream cluster API image
  Makefile
  build/apiserver-builder/Dockerfile
  build/clusterapi-image/Dockerfile
Labels: lgtm, size/M

#127 Default to origin-ansible v3.9 instead of latest.
  contrib/examples/cluster.yaml
  contrib/examples/create-cluster.sh
Labels: lgtm, size/XS

#124 Add dev notes on working with openshift-ansible.
  README.md
Labels: lgtm, retest-not-required-docs-only, size/M

#120 Add labels for owner relationships
  cmd/cluster-operator-apiserver/app/testing/server_test.go
  contrib/examples/cluster.yaml
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/validation/cluster.go
  pkg/apis/clusteroperator/validation/cluster_test.go
  pkg/controller/accept/accept_controller.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/cluster_controller_test.go
  pkg/controller/components/components_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/controller_utils_test.go
  pkg/controller/infra/infra_controller.go
  pkg/controller/infra/infra_controller_test.go
  pkg/controller/jobcontrol.go
  pkg/controller/jobcontrol_test.go
  pkg/controller/jobsync.go
  pkg/controller/jobsync_test.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/master/master_controller.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/cluster/storage_test.go
  test/integration/controller_test.go
  test/integration/jobutils.go
Labels: lgtm, size/XL
