Repository openshift/cluster-operator, pull requests merged in 2018-08, with the labels that each got.

#310 aws client setup refactor
  pkg/clusterapi/aws/actuator.go
  pkg/clusterapi/aws/actuator_test.go
  pkg/clusterapi/aws/client.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/awselb/aws_elb_controller_test.go
  pkg/controller/controller_utils.go
Labels: lgtm, size/M

#309 Add controller to link machines to nodes and apply labels + taints.
  Makefile
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-common.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-development.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-production.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-operator-remote-controllers-template-dev.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-operator-remote-controllers-template.yaml
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  contrib/examples/cluster-deployment-template.yaml
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/nodelink/node_link_controller.go
  pkg/controller/nodelink/node_link_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/XXL

#312 Consolidate aws-machine-controller into cluster-operator binary
  Makefile
  build/aws-machine-controller/Dockerfile
  build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-development.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/.gitignore
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/machine-controller-template-dev.yaml
  build/cluster-operator-ansible/playbooks/cluster-api-prep/files/machine-controller-template.yaml
  build/cluster-operator/Dockerfile
  cmd/aws-machine-controller/app/machine-controller.go
  cmd/aws-machine-controller/machine-controller.go
  cmd/cluster-operator/aws-machine-controller.go
  cmd/cluster-operator/main.go
  contrib/ansible/deploy-playbook.yml
  contrib/examples/cluster-api-controllers-template.yaml
Labels: lgtm, size/L

#314 Add support for cluster delete-after annotation.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/M

#315 Use pre-built images instead of BuildConfig
  contrib/ansible/deploy-playbook.yml
  contrib/examples/cluster-api-controllers-template.yaml
  contrib/examples/cluster-operator-template.yaml
Labels: lgtm, size/M

#316 Use Red Hat base images
  Makefile
  build/build-image/Dockerfile
  build/cluster-operator/Dockerfile
  build/fake-machine-controller/Dockerfile
  build/fake-openshift-ansible/Dockerfile
  build/playbook-mock/Dockerfile
Labels: lgtm, size/S

#318 Changes related to getting on ci-operator
  Makefile
  build/cluster-operator-ansible/Dockerfile
  build/test-image/Dockerfile
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
  contrib/pkg/cluster/waitforcluster.go
  test/integration/controller_test.go
Labels: lgtm, size/M

#313 Set ELB registration status as a condition within machine provider status.
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/controller/awselb/aws_elb_controller.go
  pkg/controller/awselb/aws_elb_controller_test.go
  pkg/controller/controller_utils.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/L

#297 registry infra controller
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  contrib/ansible/create-cluster-playbook.yml
  contrib/examples/cluster-deployment-template.yaml
  pkg/ansible/generate.go
  pkg/ansible/generate_test.go
  pkg/ansible/jobgeneratorexecutor.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/types.go
  pkg/clusterapi/aws/client.go
  pkg/clusterapi/aws/mock/client_generated.go
  pkg/controller/clusterinstall/controller.go
  pkg/controller/components/components_controller.go
  pkg/controller/controller_utils.go
  pkg/controller/registryinfra/registryinfra_controller.go
  pkg/controller/registryinfra/registryinfra_controller_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_test.go
Labels: lgtm, size/XXL

#319 Remove standalone wait utility
  Makefile
  contrib/cmd/wait-for-cluster-ready/waitforcluster.go
Labels: lgtm, size/XL

#320 Utility to build AMI
  contrib/cmd/coutil/main.go
  contrib/pkg/amibuild/command.go
  contrib/pkg/amibuild/generate.go
  contrib/pkg/amibuild/run.go
  contrib/pkg/amiid/getid.go
Labels: lgtm, size/XL

#322 Add coutil binary to cluster operator image
  build/cluster-operator/Dockerfile
Labels: lgtm, size/XS

#324 Fix indent for cluster version vars
  pkg/ansible/generate.go
Labels: lgtm, size/S

#326 Overwrite roles only for ansible v3.9
  Makefile
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/Dockerfile.v3.10
  build/cluster-operator-ansible/Dockerfile.v3.9
  build/cluster-operator-ansible/roles.v3_9/openshift_aws/tasks/security_group.yml
Labels: lgtm, size/S

#329 Install git in origin ansible 3.10 image
  build/cluster-operator-ansible/Dockerfile.v3.10
Labels: lgtm, size/XS

#328 Set openshift_master_cluster_hostname as internal elb hostname.
  build/cluster-operator-ansible/playbooks/cluster-operator/aws/install_masters.yml
Labels: lgtm, size/S

#330 Add coutil as a dependency to cluster-operator image target
  Makefile
Labels: lgtm, size/XS

#331 Fix IAM role creation with openshift-ansible v3.11
  Makefile
  build/cluster-operator-ansible/Dockerfile
  build/cluster-operator-ansible/playbooks.v3_11/cluster-operator/aws/infrastructure.yml
Labels: lgtm, size/M

#333 Add Etcd image field to ClusterVersion
  pkg/ansible/generate.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/openapi/openapi_generated.go
Labels: lgtm, size/S

#325 Add route53 hosted zone controller.
  cmd/cluster-operator-controller-manager/app/controllermanager.go
  cmd/cluster-operator-controller-manager/app/options/options.go
  pkg/apis/clusteroperator/register.go
  pkg/apis/clusteroperator/types.go
  pkg/apis/clusteroperator/v1alpha1/register.go
  pkg/apis/clusteroperator/v1alpha1/types.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusteroperator/validation/dnszone.go
  pkg/apis/clusteroperator/validation/dnszone_test.go
  pkg/apis/clusteroperator/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/client/clientset_generated/clientset/typed/clusteroperator/v1alpha1/clusteroperator_client.go
  pkg/client/clientset_generated/clientset/typed/clusteroperator/v1alpha1/dnszone.go
  pkg/client/clientset_generated/clientset/typed/clusteroperator/v1alpha1/fake/fake_clusteroperator_client.go
  pkg/client/clientset_generated/clientset/typed/clusteroperator/v1alpha1/fake/fake_dnszone.go
  pkg/client/clientset_generated/clientset/typed/clusteroperator/v1alpha1/generated_expansion.go
  pkg/client/clientset_generated/internalclientset/typed/clusteroperator/internalversion/clusteroperator_client.go
  pkg/client/clientset_generated/internalclientset/typed/clusteroperator/internalversion/dnszone.go
  pkg/client/clientset_generated/internalclientset/typed/clusteroperator/internalversion/fake/fake_clusteroperator_client.go
  pkg/client/clientset_generated/internalclientset/typed/clusteroperator/internalversion/fake/fake_dnszone.go
  pkg/client/clientset_generated/internalclientset/typed/clusteroperator/internalversion/generated_expansion.go
  pkg/client/informers_generated/externalversions/clusteroperator/v1alpha1/dnszone.go
  pkg/client/informers_generated/externalversions/clusteroperator/v1alpha1/interface.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/internalversion/clusteroperator/internalversion/dnszone.go
  pkg/client/informers_generated/internalversion/clusteroperator/internalversion/interface.go
  pkg/client/informers_generated/internalversion/generic.go
  pkg/client/listers_generated/clusteroperator/internalversion/dnszone.go
  pkg/client/listers_generated/clusteroperator/internalversion/expansion_generated.go
  pkg/client/listers_generated/clusteroperator/v1alpha1/dnszone.go
  pkg/client/listers_generated/clusteroperator/v1alpha1/expansion_generated.go
  pkg/clusterapi/aws/client.go
  pkg/clusterapi/aws/mock/client_generated.go
  pkg/controller/route53hostedzone/route53hostedzone_controller.go
  pkg/controller/route53hostedzone/route53hostedzone_controller_test.go
  pkg/controller/route53hostedzone/test_helpers.go
  pkg/controller/route53hostedzone/zonereconciler.go
  pkg/controller/route53hostedzone/zonereconciler_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/clusteroperator/dnszone/storage.go
  pkg/registry/clusteroperator/dnszone/storage_test.go
  pkg/registry/clusteroperator/dnszone/strategy.go
  pkg/registry/clusteroperator/dnszone/strategy_test.go
  pkg/registry/clusteroperator/rest/storage_cluster_operator.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Labels: lgtm, size/XXL
